#ddev-generated
services:
  openai-edge-tts:
    container_name: ddev-${DDEV_SITENAME}-openai-edge-tts
    image: ${OPENAI_EDGE_TTS_DOCKER_IMAGE:-ddev/ddev-utilities:latest}
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
